### ISSUE TITLE
Extract settings DSL into a library

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-tpolecat#104]
Briefly discussed on the Discord. This would allow sharing with the mill version of this plugin, and would also open the door for e.g. sbt-typelevel-settings to reuse this while integrating with sbt in a different way. Essentially I think it would be extracting the "unopinionated" part of this plugin from the "opinionated" :P

**Comment by DavidGregory084** [comment]
This is kind of done as we now have https://github.com/typelevel/scalac-options, but I'm going to leave this open until #107 lands.
