### ISSUE TITLE
`-Wnonunit-statement` seems not to work for scala-3 (3.3.3) 

### ISSUE THREAD

**Issue by froth** [typelevel/sbt-tpolecat#208]
I created the following reproducing example:
https://github.com/froth/sbt-tpolecat-reproducer

I added the plugin to the build:
https://github.com/froth/sbt-tpolecat-reproducer/blob/main/project/plugins.sbt

And created code that should warn(but does not):
https://github.com/froth/sbt-tpolecat-reproducer/blob/main/src/main/scala/example/ShouldWarn.scala#L6

But if I add the following line to sbt it does warn: `scalacOptions += "-Wnonunit-statement"`
(https://github.com/froth/sbt-tpolecat-reproducer/blob/main/build.sbt#L9)

Running `sbt tpolecatScalacOptions` however contains `ScalacOption(-Wnonunit-statement)` and therefore I am really confused what exactly is wrong.

**Comment by froth** [comment]
This has already been fixed in main (https://github.com/typelevel/sbt-tpolecat/commit/c48d7d9ddaac861df020ee4637ace5f8e5728db6) @TonioGela would it be possible to cut a new release?

**Comment by TonioGela** [comment]
> This has already been fixed in main ([c48d7d9](https://github.com/typelevel/sbt-tpolecat/commit/c48d7d9ddaac861df020ee4637ace5f8e5728db6)) @TonioGela would it be possible to cut a new release?

`0.5.1` has been released

**Comment by froth** [comment]
Thanks! 😊
