### ISSUE TITLE
Scala 3.5.0  -Ykind-projector is deprecated

### ISSUE THREAD

**Issue by Dichotomia** [typelevel/sbt-tpolecat#223]
Option -Ykind-projector is deprecated: Use -Xkind-projector instead

**Comment by lenguyenthanh** [comment]
fixed in #227

**Comment by Dichotomia** [comment]
Hello. 
Thanks for this work ! 
Would it be possible to release a version with this fix?
Best regards

**Comment by lenguyenthanh** [comment]
hey, I just created a release for it: https://github.com/typelevel/sbt-tpolecat/releases/tag/v0.5.2 hope it goes through soon 🤞
