### ISSUE TITLE
Combine with mill-tpolecat

### ISSUE THREAD

**Issue by davesmith00000** [typelevel/sbt-tpolecat#241]
A few years ago @DavidGregory084 heroically ported sbt-tpolecat to [mill-tpolecat](https://github.com/DavidGregory084/mill-tpolecat), but it seems to have been left behind.

There is some setup to do, but it is possible to cross publish plugins to both sbt and Mill. It would be great to keep the two in sync. One issue that I wouldn't know how to start tackling if anyone did such a thing, would be the repo name... 😉 

An alternative approach, perhaps, would be to publish a canonical list of recommended flags as a separate library, cross published to Scala 2.12, 2.13, and 3, divorced from any one build tool, so that it could be used by tool specific projects. Then the Mill-tpolecat lib could consume `sbt-tpolecat-flags`, as could other build tools or even individuals on an ad-hoc basis if they prefer.

**Comment by lenguyenthanh** [comment]
> An alternative approach, perhaps, would be to publish a canonical list of recommended flags as a separate library

Hi Dave, this is already a thing, We have [scalac-options](https://github.com/typelevel/scalac-options/blob/main/lib/src/main/scala/org/typelevel/scalacoptions/ScalacOptions.scala#L885) which contains recommended scalac options across scala versions. `sbt-tpolecat` uses it under the hood, but it seems `mill-tpolecat` doesn't use it yet. Maybe We should use `scalac-options` in `mill-tpolecat` as well.

**Comment by davesmith00000** [comment]
Works like a charm, thanks @lenguyenthanh, example from my project for the curious:

```scala
...
import $ivy.`org.typelevel::scalac-options:0.1.7`, org.typelevel.scalacoptions._

trait ShaderModule extends MillIndigo {
  def scalaVersion   = "3.5.0"
  def scalaJSVersion = "1.17.0"

  override def scalacOptions = T {
    super.scalacOptions() ++
      ScalacOptions.defaultTokensForVersion(ScalaVersion.unsafeFromString(scalaVersion())) ++
      Seq("-Xfatal-warnings")
  }
..
```

I'll close this issue, but would it be worth updating the readme with a Mill example?

**Comment by davesmith00000** [comment]
PR in ScalacOptions.
https://github.com/typelevel/scalac-options/pull/150

**Comment by davesmith00000** [comment]
PR in sbt-tpolecat
https://github.com/typelevel/sbt-tpolecat/pull/242

**Comment by davesmith00000** [comment]
PR in mill-tpolecat that I'm only 50% confident will work... but maybe someone will help me. 😅 
https://github.com/DavidGregory084/mill-tpolecat/pull/54
