### ISSUE TITLE
ScalacOption case class unreachable from build.sbt

### ISSUE THREAD

**Issue by mihaisoloi** [typelevel/sbt-tpolecat#65]
In order to use ScalacOption you need to import it via the `_root_.io.github.davidgregory084.ScalacOption` otherwise sbt looks for it in `sbt.io.github.davidgregory084.ScalacOption`.

Using it is useful for undefined DSL scalacOptions

**Comment by mihaisoloi** [comment]
perhaps we should have a:
```scala
def undefinedOption(name: String) = new ScalacOption(List(name))
```
in the ScalacOptions

**Comment by DavidGregory084** [comment]
Yeah you are right, unfortunately this affects anything published under `io.github` because sbt imports `sbt.io` into `build.sbt` by default. 😞
